#!/usr/bin/env bash
source ./bin/dev-set &&
  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-txt.bash" &&
  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-fmt.bash" &&
  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-module-fs.bash" &&
  source "${DEV_LIB_BASHLIB64_TARGET}/bashlib64-core.bash" || exit 1

function my_deploy() {
  bl64_dbg_app_show_function
  # X_CODE_PLACEHOLDER_X
}

function my_initialize() {
  bl64_dbg_app_show_function
  dev_base_task_initialize
  # X_INITIALIZE_PLACEHOLDER_X
}

bl64_lib_script_version_set '1.0.0'
bl64_msg_help_about_set 'X_ABOUT_PLACEHOLDER_X'
dev_base_initialize && my_initialize || exit $?

bl64_msg_show_batch_start "$BL64_SCRIPT_ID"
my_deploy
bl64_msg_show_batch_finish $? "$BL64_SCRIPT_ID"
